bind = ":8889"
rpc = "127.0.0.1:26657"
dev = true
metrics = true
chainId = "386"
versions = [3]
startHeight = 1
tgsBaseURL = "http://api.dev.crycx.com:8080"

[limiter]
interval = "0h0m1s"
capacity = 100

